main: io.github.evercraftmc.core.impl.spigot.ECSpigotPluginLoader

name: "EverCraft"
description: "The EverCraft plugin"
version: "${version}"

authors: [ "Kale-Ko" ]
website: "https://github.com/EverCraftMC/EverCraft"

api-version: "1.20"
load: STARTUP